# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "alpha-installer"
  s.version = "0.0.1.alpha"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matthew Solt"]
  s.date = "2013-03-09"
  s.description = "Alpha Installer is a command line application for automatic configuration and deployment of the Alpha application."
  s.email = "mattsolt@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".rspec",
    ".yardopts",
    "Gemfile",
    "Guardfile",
    "LICENSE",
    "README.md",
    "Rakefile",
    "lib/alpha-installer.rb",
    "lib/alpha_installer/base.rb",
    "lib/alpha_installer/version.rb",
    "spec/alpha_installer_spec.rb",
    "spec/cassettes/.gitkeep",
    "spec/fixtures/.gitkeep",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/activefx/alpha-installer"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Alpha Installer is a command line application for automatic configuration and deployment of the Alpha application."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<heroku-api>, [">= 0"])
      s.add_runtime_dependency(%q<fog>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.13"])
      s.add_development_dependency(%q<excon>, ["~> 0.19"])
      s.add_development_dependency(%q<listen>, [">= 0.4.7"])
      s.add_development_dependency(%q<guard>, ["~> 1.6"])
      s.add_development_dependency(%q<guard-rspec>, [">= 0"])
      s.add_development_dependency(%q<vcr>, ["~> 2.4"])
      s.add_development_dependency(%q<webmock>, ["~> 1.9"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<pry>, [">= 0"])
    else
      s.add_dependency(%q<heroku-api>, [">= 0"])
      s.add_dependency(%q<fog>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.13"])
      s.add_dependency(%q<excon>, ["~> 0.19"])
      s.add_dependency(%q<listen>, [">= 0.4.7"])
      s.add_dependency(%q<guard>, ["~> 1.6"])
      s.add_dependency(%q<guard-rspec>, [">= 0"])
      s.add_dependency(%q<vcr>, ["~> 2.4"])
      s.add_dependency(%q<webmock>, ["~> 1.9"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<pry>, [">= 0"])
    end
  else
    s.add_dependency(%q<heroku-api>, [">= 0"])
    s.add_dependency(%q<fog>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.13"])
    s.add_dependency(%q<excon>, ["~> 0.19"])
    s.add_dependency(%q<listen>, [">= 0.4.7"])
    s.add_dependency(%q<guard>, ["~> 1.6"])
    s.add_dependency(%q<guard-rspec>, [">= 0"])
    s.add_dependency(%q<vcr>, ["~> 2.4"])
    s.add_dependency(%q<webmock>, ["~> 1.9"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<pry>, [">= 0"])
  end
end

